config/routes.rb
Rails.application.routes.draw do
  # establish routes for user model in Devise gem
  devise_for :users
  
  #routes to webpages 
  #get 'page/home'
  get 'page/parents' => 'page#parents'
  get 'page/providers' => 'page#providers'
  get 'page/contacts' => 'page#contacts'
  get 'providers/profile' => 'providers#profile'
  get 'page/disorders' => 'page#disorders'
  get 'page/resources' => 'page#resources'

  get 'conditions/by_type' => 'condition_types#index'
  get 'conditions' => 'conditions#index'
  get 'conditions/:name' => 'conditions#info'

  #routes  for search
  # explanation of route: match [url of your page] => [controller#action name in controller], 
  # :via => action type (get, post, put, delete), :as => give your route an easy-to-recognize, self-defined name

  # Note: the action of your controller must match the name of the HTML page you are routing to.
  match 'search/search' => 'search#search', :via => :get, :as => :data_search
  match 'search/go_to_profile/:id' => 'search#go_to_profile', :via => :get, :as => :go_to_profile
  get "search/advanced_search"
  get "search/advanced_search_result"
  resources :search, only: [:search]

  #routes for provider model
  post 'providers/create' => 'providers#create'
  resources :providers
  
  #routes to admin management
  post 'admins/admin' => 'admins#admin'
  get 'admins/index' => 'admins#index'
  
  match "admins/update/:id" => "admins#update", :via => :put, :as => :admin_update_account
  match 'admins/destroy_user/:id' => "admins#destroy_user", :via => :delete, :as => :admins_destroy_user
  match "admins/new_account" => "admins#new_account", :via => :get, :as => :admin_new_account
  match "admins/create_account" => "admins#create_account", :via => :post, :as => :admin_create_account
  match "admins/show/:id" => "admins#show", :via => :get, :as => :admin_show_account
  match "admins/edit/:id" => "admins#edit", :via => :get, :as => :admin_edit_account
  #get 'admins/update/:id' => 'admins#update'
  
  #routes to create/update services for a provider
  match "services/new/:id" => "services#new", :via => :get, :as => :new_service
  match "services/create" => "services#create", :via => :post, :as => :create_service
  match "services/edit/:id" => "services#edit", :via => :get, :as => :edit_service
  match "services/update/:id" => "services#update", :via => :put, :as => :update_service
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # post and get methods should be defined separately
  root 'page#home'
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_and_belongs_to_many :waivers
  has_and_belongs_to_many :services
  has_and_belongs_to_many :insurances

  validates :name,  presence: true
  validates :address, presence: true
  validates :phone, presence: true

  scope :by_services, -> (service_ids) {
    joins(:services).where(services: {id: service_ids }) if service_ids.present?
  }

  scope :by_insurances, -> (insurance_ids) {
    joins(:insurances).where(insurances: {id: insurance_ids }) if insurance_ids.present?
  }

  scope :by_waivers, -> (waiver_ids) {
    joins(:waivers).where(waivers: {id: waiver_ids }) if waiver_ids.present?
  }

  include PgSearch::Model
  # provider search by name (from the nav bar)
  pg_search_scope :search_name, against: [:name], using: {
                    tsearch: { prefix: true }
                  }

  def self.search(query)
    if query.present?
      search_name(query)
    else
      order(name: :asc)
    end
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
    before_action :authenticate_user!

    include CheckboxParams
    
    def new
      @insurance_params = insurance_params
      @waiver_params = waiver_params
      @provider = Provider.new
    	render new_provider_path
    end
    
    def create
      if Provider.find_by_id(current_user.id)
        flash[:errors] = ["You already have a provider profile!"]
        redirect_to providers_profile_path
      else
        @p = Provider.new(provider_params)
        if @p.save!
          flash[:success] = "Profile created!"
          redirect_to providers_profile_path
        else
          flash[:errors] = @p.errors.full_messages
          render new_provider_path
        end
      end
    end
    
    def edit
      @provider = Provider.find(params[:id])
      @insurance_params = insurance_params
      @waiver_params = waiver_params
    end
    
    def update
      @provider = Provider.find(params[:id])
      if @provider.update_attributes(provider_params)
        flash[:success] = ["Profile updated!"]
        if current_user.is_admin?
          redirect_to admins_index_path
        else
          redirect_to providers_profile_path
        end
      else
        flash.now[:errors] = @provider.errors.full_messages
        render 'edit'
      end
    end
    
    private

    def provider_params
      params.require(:provider).permit(:id, :name, :address, :phone, :description, :waiver => [], :insurance => [])
    end
    

end

app/views/providers/_profile.html.erb
<div class="pc_profile">
    <%= render 'providers/shared/success_message' %>
    <%= render 'providers/shared/error_messages' %>
    <div id="w">
      <div id="content" class="clearfix">
          <p class="long-header" style="font-size: 50px;"><%= p.name %></p>
      <nav id="profiletabs">
        <ul class="clearfix">
          <li><a href="#description" class="sel">Description</a></li>
          <li><a href="#info">Basic info</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#insurances">Insurances</a></li>
          <li><a href="#waivers">Waivers</a></li>
          <% if can_edit && user_signed_in? && p.id = current_user.id %>
          <li><%= link_to('Edit Profile', edit_provider_path(p), method: :GET) %></li>
          <li><%= link_to('Add Service', new_service_path(p), method: :GET) %></li>
          <% end %>
        </ul>
      </nav>

      <section class="tab-header" id="description">
        <p><%= p.description %></p>
      </section>

      <section class="hidden tab-header" id="info">
        <p class="setting"><span>E-mail Address </span> <%= p.email %> </p>
        <p class="setting"><span>Address </span> <%= p.address %> </p>
        <p class="setting"><span>Phone </span> <%= p.phone %> </p>
      </section>

      <section class="hidden tab-header" id="services">
        <% p.services.each do |service| %>
          <div class="service-title">
            <h2 class="service-name"><%= service.name %></h2>
          </div>
          <% if can_edit  %>
            <%= link_to('Edit this service', edit_service_path(service), method: :get) %></div>
          <% end %>
          <p class="service-description"><%= service.description %></p>
        <% end %>
      </section>

      <section class="hidden tab-header" id="insurances">
        <% p.insurances.each do |insurance| %>
          <div class="insurance-title">
            <h2 class="insurance-name"><%= insurance.name %></h2>
          </div>
          <p class="insurance-phone"><%= "Phone: #{insurance.phone}" %>
        <% end %>
      </section>

      <section class="hidden tab-header" id="waivers">
        <% p.waivers.each do |waiver| %>
          <div class="waiver-title">
            <h2 class="waiver-name"><%= waiver.name %></h2>
          </div>
          <p class="waiver-description">No desciption</p>
        <% end %>
      </section>

    </div><!-- @end #content -->
</div><!-- @end #w -->
</div>

  <!-- MOBILE VERSION -->
  <!-- grid classes  -->
  <div class="mobile-profile">
    <p class="long-header" style="padding-bottom: 0; margin-bottom: 0;margin-top: 10;" ><%= p.name %></p>
    <!-- Grid row -->
    <div class="row accordion-gradient-bcg d-flex justify-content-center" >
      <!-- Grid column -->
      <div class="col-md-5 col-xl-6 py-5">
    <!--Accordion wrapper-->
    <div class="accordion md-accordion accordion-2" id="accordionEx7" role="tablist" aria-multiselectable="true" >

  <!-- Description card -->
  <div class="card" >

    <!-- Description header -->
    <div class="card-header" role="tab" id="headingOne1">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapse1"
        aria-expanded="false" aria-controls="collapse1">
        <h5 class="mb-0 white-text font-thin"> Description <i class="fas fa-angle-down rotate-icon"></i></h5>
      </a>
    </div>

    <!-- Description body -->
  <div>
    <div id="collapse1" class="collapse" role="tabpanel" aria-labelledby="headingOne1" data-parent="#accordionEx">
      <div class="card-body card-body mb-1 rgba-grey-light white-text">
        <p><%= p.description %></p>
      </div>
    </div>
  </div>
  <!-- Basic Info card -->
  <div class="card">

    <!-- Basic Info header -->
    <div class="card-header" role="tab" id="headingTwo2">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseTwo2"
        aria-expanded="false" aria-controls="collapseTwo2">
        <h5 class="mb-0">Basic Info <i class="fas fa-angle-down rotate-icon"></i>
        </h5>
      </a>
    </div>

    <!-- Basic Info body -->
    <div id="collapseTwo2" class="collapse" role="tabpanel" aria-labelledby="headingTwo2" data-parent="#accordionEx">

      <div class="card-body">
        <p class="setting"><span>E-mail Address </span></br> <%= p.email %> </p>
        <p class="setting"><span>Address </span></br> <%= p.address %> </p>
        <p class="setting"><span>Phone </span> </br><%= p.phone %> </p>

        <% if false %>
        <p class="setting"><span>Waivers </span></br> <%= p.waivers.join(", ") %> </p>
        <p class="setting"><span>Insurances </span></br> <%= p.insurance.join(", ") %> </p>
        <% end %>

      </div>
    </div>
  </div>

  <!-- Service card -->
  <div class="card">

    <!-- Service header -->
    <div class="card-header" role="tab" id="headingThree3">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree3"
        aria-expanded="false" aria-controls="collapseThree3">
        <h5 class="mb-0">
          Services <i class="fas fa-angle-down rotate-icon"></i>
        </h5>
      </a>
    </div>

    <!-- Service body -->
    <div id="collapseThree3" class="collapse" role="tabpanel" aria-labelledby="headingThree3" data-parent="#accordionEx">
      <div class="card-body">
        <% @s = Service.where(id: p.id) %>
        <% @s.each do |service| %>
          <div class="service-title"><h2 class="service-name"><%= service.name %></h2></div>
          <% if can_edit %>
            <%= link_to('Edit this service', edit_service_path(service), method: :get) %></div>
          <% end %>
          <p class="service-description"><%= service.description %></p>
        <% end %>
      </div>
    </div>

  <% if can_edit %>
  <!-- Edit Profile card -->
  <div class="card" >

    <!-- Edit Profile header -->
    <div class="card-header" role="tab" id="headingFour4">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseFour4"
        aria-expanded="false" aria-controls="collapseFour4">
        <h5 class="mb-0 white-text font-thin"> Edit Profile <i class="fas fa-angle-down rotate-icon"></i></h5>
      </a>
    </div>

    <!-- Edit Profile body -->
  <div>
    <div id="collapseFour4" class="collapse" role="tabpanel" aria-labelledby="headingFour4" data-parent="#accordionEx">
      <div class="card-body card-body mb-1 rgba-grey-light white-text">
  <%= link_to('Edit Profile', edit_provider_path(p), method: :GET) %>
    </div>
  </div>

  <!-- Add Service card -->
  <div class="card" >

    <!-- Add Service header -->
    <div class="card-header" role="tab" id="headingFive5">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseFive5"
        aria-expanded="false" aria-controls="collapseFive5">
        <h5 class="mb-0 white-text font-thin"> Add Service <i class="fas fa-angle-down rotate-icon"></i></h5>
      </a>
    </div>

    <!-- Add Service body -->
  <div>
    <div id="collapseFive5" class="collapse" role="tabpanel" aria-labelledby="headingFive5" data-parent="#accordionEx">
      <div class="card-body card-body mb-1 rgba-grey-light white-text">
          <%= link_to('Add Service', new_service_path(p), method: :GET) %>
    </div>
    </div>

</div>
  </div>
  <% end %>
<!-- Accordion wrapper -->
</div>
  <!-- Grid column -->

</div>
</div>
</div> <!-- Mobile profile -->

</div>
</div>

</div>

<%= javascript_include_tag "profile" %>

app/views/providers/edit.html.erb
<div class="login-page">
<%= form_for @provider, :url => {:controller => 'providers', :action => 'update' } do |f| %>
 <%= render 'providers/shared/success_message' %>
 <%= render 'providers/shared/error_messages' %>
 <div class="field">
 <%= f.label "name" %>
 <%= f.text_field :name %>
 </div>
 
 <div class="field">
 <%= f.label :address %>
 <%= f.text_field :address %>
 </div>
 
 <div class="field">
 <%= f.label :phone %>
 <%= f.text_field :phone %>
 </div>
 
  <div class="field">
    <%= f.label :insurance %>
    <div class="field checkbox_field">
    <% @insurance_params.each do |i| %>
     <div class="checkbox_div">
     <%= f.label i %>
     <%= f.check_box :insurances, {:multiple => true}, i, nil %>
     </div>
    <% end %>
  </div>
 </div>
 
 <div class="field">
  <%= f.label :waivers %>
  <div class="field checkbox_field">
   <% @waiver_params.each do |w| %>
   <div class="checkbox_div">
    <%= f.label w %>
    <%= f.check_box :waivers, {:multiple => true}, w, nil %>
   </div>
   <% end %>
  </div>
 </div>
  
 <div class="field">
 <%= f.label :description %>
 <em>(not exceeding 250 words)</em><br />
 <%= f.text_area :description, class: "textbox", id: 'textbox', cols: "32", rows: "10" %><br />
 </div>
 <span id="count">Word count: <span id="wordCount"></span></span>
 
 <div class="actions">
  <%= f.submit 'Update' %>
  </div>
<% end %>
</div>
<%= javascript_include_tag "textbox" %>

app/views/providers/new.html.erb
<div class="login-page">
 
<%= form_for @provider, url: '/providers/create', html: { method: :post, id: 'new_user', class: 'container'} do |f| %>
  <%= render 'providers/shared/error_messages' %>
  <div class="field">
    <%= f.label :"name" %><br />
    <%= f.text_field :name %><br />
  </div>
  
  <div class="field">
     <%= f.label :address %><br />
     <%= f.text_field :address %><br />
  </div>
  
  <div class="field">
     <%= f.label :phone %><br />
     <%= f.text_field :phone %><br />
  </div>
  
  <div class="field">
       <div class="field checkbox_field">
      		 <%= f.label :insurance %>
           <% @insurance_params.each do |i| %>
           <div class="checkbox_div">
           <%= f.label i %>
           <%= f.check_box :insurances, {:multiple => true}, i, nil %>
           </div>
           <% end %>
       </div>
  </div>
  
  <div class="field">
      <div class="field checkbox_field">
      	<%= f.label :waivers %>
      	<div class="field checkbox_field">
       	<% @waiver_params.each do |w| %>
       	<div class="checkbox_div">
        <%= f.label w %>
        <%= f.check_box :waivers, {:multiple => true}, w, nil %>
       </div>
       <% end %>
    </div>
  </div>

   <div class="field">
    <%= f.label :description %>
    <em>(not exceeding 250 words)</em><br />
     <%= f.text_area :description, class: "textbox", id: 'textbox', cols: "32", rows: "10"%><br />
  </div>
  <span id="count">Word count: <span id="wordCount"></span></span>

    <%= hidden_field_tag "provider[id]", "#{current_user.id}" %>
  <div class="actions">
    <%= f.submit "Submit profile" %>
  </div>
<% end %>
</div>
<%= javascript_include_tag "textbox" %>

app/views/providers/profile.html.erb
<%= render "profile", p: p, can_edit: true %>