config/routes.rb
Rails.application.routes.draw do
  # establish routes for user model in Devise gem
  devise_for :users
  
  #routes to webpages 
  #get 'page/home'
  get 'page/parents' => 'page#parents'
  get 'page/providers' => 'page#providers'
  get 'page/contacts' => 'page#contacts'
  get 'providers/profile' => 'providers#profile'
  get 'page/disorders' => 'page#disorders'
  get 'page/resources' => 'page#resources'

  get 'conditions/by_type' => 'condition_types#index'
  get 'conditions' => 'conditions#index'
  get 'conditions/:name' => 'conditions#info'

  #routes  for search
  # explanation of route: match [url of your page] => [controller#action name in controller], 
  # :via => action type (get, post, put, delete), :as => give your route an easy-to-recognize, self-defined name

  # Note: the action of your controller must match the name of the HTML page you are routing to.
  match 'search/search' => 'search#search', :via => :get, :as => :data_search
  match 'search/go_to_profile/:id' => 'search#go_to_profile', :via => :get, :as => :go_to_profile
  get "search/advanced_search"
  get "search/advanced_search_result"
  resources :search, only: [:search]

  #routes for provider model
  post 'providers/create' => 'providers#create'
  resources :providers
  
  #routes to admin management
  post 'admins/admin' => 'admins#admin'
  get 'admins/index' => 'admins#index'
  
  match "admins/update/:id" => "admins#update", :via => :put, :as => :admin_update_account
  match 'admins/destroy_user/:id' => "admins#destroy_user", :via => :delete, :as => :admins_destroy_user
  match "admins/new_account" => "admins#new_account", :via => :get, :as => :admin_new_account
  match "admins/create_account" => "admins#create_account", :via => :post, :as => :admin_create_account
  match "admins/show/:id" => "admins#show", :via => :get, :as => :admin_show_account
  match "admins/edit/:id" => "admins#edit", :via => :get, :as => :admin_edit_account
  #get 'admins/update/:id' => 'admins#update'
  
  #routes to create/update services for a provider
  match "services/new/:id" => "services#new", :via => :get, :as => :new_service
  match "services/create" => "services#create", :via => :post, :as => :create_service
  match "services/edit/:id" => "services#edit", :via => :get, :as => :edit_service
  match "services/update/:id" => "services#update", :via => :put, :as => :update_service
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # post and get methods should be defined separately
  root 'page#home'
end

app/views/admins/edit.html.erb
<div class="login-page">
<%= form_for @user, html: { method: :put }, :url => {:controller => 'admins', :action => 'update' } do |f| %>
          <%= render 'providers/shared/success_message' %>
          <%= render 'providers/shared/error_messages' %>
          <div class="field">
              <%= f.label "email" %>
              <%= f.text_field :email %>
          </div>
          
          <div class="field">
            <%= f.label "Reset password" %><br />
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em><br />
            <% end %>
              <%= f.password_field :password, autofocus: true, autocomplete: "new-password" %>
          </div>
          
          <%= f.fields_for @user.provider do |u| %>
          <div class="field">
          <%= u.label "practice name" %>
          <%= u.text_field :practiceName %>
          </div>
          
          <div class="field">
          <%= u.label :address %>
          <%= u.text_field :address %>
          </div>
          
          <div class="field">
          <%= u.label :phone %>
          <%= u.text_field :phone %>
          </div>
          
          <div class="field">
          <%= u.label :insurance %>
          <div class="field checkbox_field">
          <% @insurance_params.each do |i| %>
           <div class="checkbox_div">
           <%= u.label i %>
           <%= u.check_box :insurance, {:multiple => true}, i, nil %>
           </div>
          <% end %>
          </div>
         </div>
         
          <div class="field">
          <%= u.label :waivers %>
          <div class="field checkbox_field">
           <% @waiver_params.each do |w| %>
           <div class="checkbox_div">
            <%= u.label w %>
            <%= u.check_box :waiver, {:multiple => true}, w, nil %>
           </div>
           <% end %>
          </div>
        </div>
          
          <div class="field">
          <%= u.label :description %>
          <em>(not exceeding 250 words)</em><br />
          <%= u.text_area :description, class: "textbox", id: 'textbox', cols: "32", rows: "10" %><br />
          </div>
          <span id="count">Word count: <span id="wordCount"></span></span>
        <% end %>
         
         
          <div class="actions">
          <%= f.submit 'Update' %>
          </div>
<% end %>
</div>
<%= javascript_include_tag "textbox" %>

app/views/admins/index.html.erb
<!--source: https://codepen.io/anon/pen/MRgQyP-->
<div class='container'>
<div id="demo">
  <h1>All Current Users</h1>
    <%= render 'providers/shared/success_message' %>
    <%= render 'providers/shared/error_messages' %>  
  <nav id='profiletabs'>
    <ul class="clearfix admin_create_button">
      <li><%= link_to 'Create new user', admin_new_account_path, method: :GET %></li>
    </ul>
  </nav>
  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>User Email</th>
          <th>Status</th>
          <th>Practice Name</th>
          <th>Address</th>
          <th>Phone</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <% @p = Provider.find_by_user_id(user.id) %>
        <tr>
          <td data-title="email"><%= user.email %></td>
          <% if user.admin? %>
              <td data-title="status">Admin</td>
              <td data-title="practiceName">N/A</td>
              <td data-title="address">N/A</td>
              <td data-title="phone">N/A</td>
          <% else %>
            <% if @p %>
              <td data-title="status">Provider</td>
              <td data-title="practiceName" class="td_practiceName"><%= @p.practiceName %></td>
              <td data-title="address"><%= @p.address %></td>
              <td data-title="phone"><%= @p.phone %></td>
            <% else %>
              <td data-title="status">Provider</td>
              <td data-title="practiceName"></td>
              <td data-title="address"></td>
              <td data-title="phone"></td>
            <% end %>
          <% end %>
          
          <% if current_user != user %>
          <td><%= link_to "Delete", admins_destroy_user_path(user), data: { confirm: "Are you sure?" }, method: :delete %></td>
          <% else %>
          <td></td>
          <% end %>
          
          <% if @p %>
          <td><%= link_to('View detail', admin_show_account_path(user), method: :GET) %></td>
          <% else %>
          <td></td>
          <% end %>
        </tr>
        <% end %>
        
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/admins/new_account.html.erb
<div class="login-page">
<%= form_for :user, url: admin_create_account_path do |f| %>
          <%= render 'providers/shared/success_message' %>
          <%= render 'providers/shared/error_messages' %>
          <div class="field">
              <%= f.label "email" %>
              <%= f.text_field :email %>
          </div>
          
          <div class="field">
            <%= f.label :password %><br />
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em><br />
            <% end %>
              <%= f.password_field :password, autofocus: true, autocomplete: "new-password" %>
          </div>
          
          <%= f.fields_for :provider do |u| %>
          <div class="field">
          <%= u.label "practice name" %>
          <%= u.text_field :practiceName %>
          </div>
          
          <div class="field">
          <%= u.label :address %>
          <%= u.text_field :address %>
          </div>
          
          <div class="field">
          <%= u.label :phone %>
          <%= u.text_field :phone %>
          </div>
          
          <div class="field">
          <%= f.label :insurance %>
          <div class="field checkbox_field">
          <% @insurance_params.each do |i| %>
           <div class="checkbox_div">
           <%= f.label i %>
           <%= f.check_box :insurance, {:multiple => true}, i, nil %>
           </div>
          <% end %>
          </div>
         </div>
          
          <div class="field">
          <%= u.label :description %>
          <em>(not exceeding 250 words)</em><br />
          <%= u.text_area :description, class: "textbox", id: 'textbox', cols: "32", rows: "10" %><br />
          </div>
          <span id="count">Word count: <span id="wordCount"></span></span>
        <% end %>
         
         
          <div class="actions">
          <%= f.submit 'Create' %>
          </div>
<% end %>
</div>
<%= javascript_include_tag "textbox" %>

app/views/admins/show.html.erb
<div class="container">
<% @provider = Provider.find_by_user_id(@user.id) %>
<h2 class="admin_show_h"><%= @provider.practiceName %></h2>
  <nav id='profiletabs'>
    <ul class="clearfix admin_create_button">
      <li><%= link_to('Edit Provider Info', admin_edit_account_path(@user), method: :GET) %></li>
    </ul>
  </nav>
  
<span class="admin_show_line">Email: <%= User.find(@provider.user_id).email %></span>
<span class="admin_show_line">Phone: <%= @provider.phone %></span>
<span class="admin_show_line">Address: <%= @provider.address %></span>
<span class="admin_show_line">Description: </span>
<div class="admin_show_p"><%= @provider.description %></div>
<span class="admin_show_line">Waivers</span>
<span class="admin_show_line">Services</span>
</div>