config/routes.rb
Rails.application.routes.draw do
  # establish routes for user model in Devise gem
  devise_for :users
  
  #routes to webpages 
  #get 'page/home'
  get 'page/parents' => 'page#parents'
  get 'page/providers' => 'page#providers'
  get 'page/contacts' => 'page#contacts'
  get 'providers/profile' => 'providers#profile'
  get 'page/disorders' => 'page#disorders'
  get 'page/resources' => 'page#resources'

  get 'conditions/by_type' => 'condition_types#index'
  get 'conditions' => 'conditions#index'
  get 'conditions/:name' => 'conditions#info'

  #routes  for search
  # explanation of route: match [url of your page] => [controller#action name in controller], 
  # :via => action type (get, post, put, delete), :as => give your route an easy-to-recognize, self-defined name

  # Note: the action of your controller must match the name of the HTML page you are routing to.
  match 'search/search' => 'search#search', :via => :get, :as => :data_search
  match 'search/go_to_profile/:id' => 'search#go_to_profile', :via => :get, :as => :go_to_profile
  get "search/advanced_search"
  get "search/advanced_search_result"
  resources :search, only: [:search]

  #routes for provider model
  post 'providers/create' => 'providers#create'
  resources :providers
  
  #routes to admin management
  post 'admins/admin' => 'admins#admin'
  get 'admins/index' => 'admins#index'
  
  match "admins/update/:id" => "admins#update", :via => :put, :as => :admin_update_account
  match 'admins/destroy_user/:id' => "admins#destroy_user", :via => :delete, :as => :admins_destroy_user
  match "admins/new_account" => "admins#new_account", :via => :get, :as => :admin_new_account
  match "admins/create_account" => "admins#create_account", :via => :post, :as => :admin_create_account
  match "admins/show/:id" => "admins#show", :via => :get, :as => :admin_show_account
  match "admins/edit/:id" => "admins#edit", :via => :get, :as => :admin_edit_account
  #get 'admins/update/:id' => 'admins#update'
  
  #routes to create/update services for a provider
  match "services/new/:id" => "services#new", :via => :get, :as => :new_service
  match "services/create" => "services#create", :via => :post, :as => :create_service
  match "services/edit/:id" => "services#edit", :via => :get, :as => :edit_service
  match "services/update/:id" => "services#update", :via => :put, :as => :update_service
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # post and get methods should be defined separately
  root 'page#home'
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :waivers
  has_and_belongs_to_many :conditions
  has_and_belongs_to_many :providers
end

app/models/waiver.rb
class Waiver < ApplicationRecord
  has_and_belongs_to_many :services
  has_and_belongs_to_many :providers
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include CheckboxParams

  def search
    if params[:query].present?
      @results = Provider.search(params[:query])
    else
      @results = Provider.order(name: :asc)
    end
  end

  def go_to_profile
    @provider = Provider.find(params[:id])
  end

  def advanced_search_result
    name = params[:name]
    services = params[:query][:service_ids].select { |e| e != "" }
    insurances = params[:query][:insurance_ids].select { |e| e != "" }
    waivers = params[:query][:waiver_ids].select { |e| e != "" }

    if ([name, services, insurances, waivers].count{ |q| q.blank? }) == 4
      @results = Provider.order(name: :asc)
    else
      @results = Provider.by_services(services)
                         .by_insurances(insurances)
                         .by_waivers(waivers)
                         .search(name)
                         .uniq
    end
  end
end

app/views/search/_search_results.html.erb
<!--source: https://codepen.io/anon/pen/MRgQyP-->
<div class='container'>
<div id="demo">
    <p class="long-header" >Search Results</p>
    <% if @results.any? %>
  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <!-- Column titles in search results -->
        <tr>
          <th>Practice Name</th>
          <th>See Profile</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>
        <!-- Column data in search results -->
        <% @results.each do |result| %>
        <tr>
          <td data-title="Provider Name"><%= result.name %></td>
            <td><%= link_to('Profile', go_to_profile_path(result.id), method: :GET) %></td>
            <td data-title="phone"><%= result.phone %></td>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>
  <% else %>
  <h1>No results!</h1>
  <% end %>
</div>
</div>

app/views/search/advanced_search.html.erb
<!--
To understand advanced search, look at:
1. /nami_website/app/controllers/search_controller.rb
2. /nami_website/app/helpers/checkbox_params.rb
3. /nami_website/app/views/search/advanced_search_result.html.erb
-->

<!-- fieldset is used for grouping elements in forms and also for assessibility, a screen reader will read off the legend.-->
<form action='/search/advanced_search_result' class= "advanced_search">
  <p class="long-header" >Advanced Search</p>
  <div class="form-group centered">
    <input class="form-control col-xs-8 col-md-6 col-lg-6" name="name" id = "name" placeholder="Search by Provider Name" type="text">
    <div class="input-group-btn">
      <button class="btn btn-default" type="submit"><i class="fas fa-search text-grey"></i></button>
    </div>
  </div>

  <fieldset>
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <div class="row heading">
            <%= label 'services', 'Services' %>
          </div>
          <div class="row">
            <div class="col-sm">
              <%= collection_check_boxes(:query, :service_ids, Service.all, :id, :name) do |s| %>
                <div class="row">
                  <div class="col-1">
                    <%= s.check_box %>
                  </div>
                  <div class="col">
                    <%= s.label %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm">
          <div class="row heading">
            <%= label 'insurances', 'Insurances' %>
          </div>
          <div class="row">
            <div class="col-sm">
              <%= collection_check_boxes(:query, :insurance_ids, Insurance.all, :id, :name) do |i| %>
                <div class="row">
                  <div class="col-1">
                    <%= i.check_box %>
                  </div>
                  <div class="col">
                    <%= i.label %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm">
          <div class="row heading">
            <%= label 'waivers', 'Waivers' %>
          </div>
          <div class="row">
            <div class="col-sm">
              <%= collection_check_boxes(:query, :waiver_ids, Waiver.all, :id, :name) do |w| %>
                <div class="row">
                  <div class="col-1">
                    <%= w.check_box %>
                  </div>
                  <div class="col">
                    <%= w.label %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </fieldset>
</form>

app/views/search/advanced_search_result.html.erb
<%= render "search/search_results" %>

app/views/search/go_to_profile.html.erb
<%= render "providers/profile", p: @provider, can_edit: false %>

app/views/search/search.html.erb
<%= render "search/search_results" %>